SRC = main.cpp Fixed.cpp
CC = c++
NAME = fixed
CFLAGS = -Wall -Wextra -Werror
SRC_O = $(SRC:.cpp=.o)
all :$(NAME)
$(NAME) : $(SRC)
	@$(CC) $(CFLAGS) $(SRC) -o $(NAME)
clean:
	@rm -f $(SRC_O)
fclean:clean
	@rm -f $(NAME)
re: fclean all

#Default constructor called
#Copy constructor called
#Copy assignment operator called // <-- This line may be missing depending on your implementation
#getRawBits member function called
#Default constructor called
#Copy assignment operator called
#getRawBits member function called
#getRawBits member function called
#0
#getRawBits member function called
#0
#getRawBits member function called
#0
#Destructor called
#Destructor called
#Destructor called